#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01
sample 02
sample 03
sample 04
sample 05

for i in {1..9}; do
    if [[ $i != 2 ]] && [[ $i != 4 ]]; then
        tc edge-0$i random_generator $i $i
    fi
done;

for i in {1..29}; do
    lo=$(($i*10))
    hi=$(($lo+9))
    tc random-$i random_generator $lo $hi
done;

tc random-40 random_generator 300 300
