#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution with_newline.py

compile random_generator.py

sample 01
sample 02
sample 03
sample 04
sample 05
sample 06

for i in {01..50}; do
tc secret-$i random_generator 0 100 -1000000 1000000
done;
