#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01
sample 02
sample 03

for i in {01..10}; do
    tc small-clean-$i random_generator 1 100 0.0 0 0
done;

for i in {11..20}; do
    tc small-mixed-$i random_generator 1 100 0.2 1 5
done;

for i in {21..30}; do
    tc big-clean-$i random_generator 101 1000 0.0 1 5
done;
for i in {31..40}; do
    tc big-mixed-$i random_generator 101 1000 0.3 5 10
done;
