#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01
sample 02

for i in {01..40}; do
tc random-$i random_generator 1 1000
done;
for i in {41..49}; do
tc random-$i random_generator 1000 100000
done;
tc random-50 random_generator 100000 100000
