#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01
sample 02
sample 03

for i in {01..15}; do
    tc random-$i random_generator 1 1000000
done;
for i in {16..20}; do
    tc random-$i random_generator 10 1000000
done;
