#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../../testdata_tools/gen.sh

use_solution bjarki_lame.py

compile random_generator.py # Arguments: method

samplegroup
sample 01
sample 02
sample 03
sample 04

group GA 20
tc 03
tc GA-01 random_generator rand 10 10 0.2
tc GA-02 random_generator rand 10 10 0.6
tc GA-03 random_generator rand 10 10 0.5
tc GA-04 random_generator rand 10 10 0.9
tc GA-05 random_generator rand 10 10 0.1
tc GA-06 random_generator rand 10 10 0.3
tc GA-07 random_generator rand 10 10 0.0
tc GA-08 random_generator rand 10 10 1.0

group GB 20
include_group GA
tc GB-01 random_generator rand 100000 2 0.2 
tc GB-02 random_generator rand 100000 2 0.5
tc GB-03 random_generator rand 100000 2 0.9

group GC 20
include_group GB
tc GC-01 random_generator rand 100000 10 0.4
tc GC-02 random_generator rand 100000 10 0.1
tc GC-04 random_generator rand 100000 10 0.5

group GD 20
include_group GA
tc 01
tc 02
tc 04
tc GD-01 random_generator rand 1000 1000 0.1
tc GD-03 random_generator rand 1000 1000 0.5
tc GD-05 random_generator rand 1000 1000 0.9

group GE 20
include_group GD
include_group GC
tc GE-01 random_generator atmost 1000000
tc GE-02 random_generator atmost 1000000
tc GE-06 random_generator atmost 1000000
tc GE-07 random_generator sqrt 1000000
tc GE-08 random_generator sqrt 1000000
