#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01
sample 02
sample 03
sample 04
sample 05
sample 06
sample 07
sample 08
sample 09

for i in {01..10}; do
    tc high-k-$i random_generator 1 20 11 20
done;

for i in {01..30}; do
    tc medium-k-$i random_generator 1 20 6 10
done;

for i in {01..60}; do
    tc low-k-$i random_generator 1 20 1 5
done;
