#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code/main.py

compile random_generator.py

# sample 01

tc secret-sample-01 random_generator 5 1
for i in {01..99}; do
    tc random-$i random_generator -1 $i 
done;
