#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample_manual 01
sample_manual 02
sample_manual 03

for i in {01..99}; do
tc random-$i random_generator 2 100000 1 5
done;

