#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01
sample 02
sample 03

for i in {01..90}; do
tc random-$i random_generator 1 10000
done;

tc edge-01 random_generator 1 1
tc edge-02 random_generator 10000 10000

