#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01
sample 02
sample 03
sample 04
sample 05

tc fixed-width-$i random_generator 1 1 1 1 fixed_width

for i in {02..30}; do
    tc fixed-width-$i random_generator 1 100 0 100 fixed_width
done;

for i in {01..30}; do
    tc no-leading-spaces-$i random_generator 1 100 0 100 no_leading_spaces
done;

for i in {01..30}; do
    tc leading-spaces-$i random_generator 1 100 0 100 leading_spaces
done;

