#!/usr/bin/env bash
PPATH=$(realpath ..)
. ../../../../testdata_tools/gen.sh

use_solution solution_code/main.py

compile random_generator.py

hint () {
    local name="$1"
    local path="$CURGROUP_DIR/$(_base ${cases[$name]})"
    echo "$2" > "$path.hint"
}

samplegroup

GAHINT="$(printf "Is it possible to construct an object of the type Height?\nThis test group only creates an instance of your class,\npassing two integers as parameters to the constructor.\n")"
group GA-height-init 20
for i in {01..10}; do
tc height-init-$i random_generator height "__init__"
hint height-init-$i "$GAHINT"
done

GENERALHINT="verifying the return type and value,\nas well as checking for unwanted side effects.\n"

GBHINT="$(printf "This test group prints an instance of your class,\n$GENERALHINT")"
group GB-height-str 20
for i in {01..10}; do
tc height-str-$i random_generator height "__str__"
hint height-str-$i "$GBHINT"
done

GCHINT="$(printf "This test group compares two instances of your class with the > operator,\n$GENERALHINT")"
group GC-height-gt 20
for i in {01..10}; do
tc height-gt-$i random_generator height "__gt__"
hint height-gt-$i "$GCHINT"
done

GDHINT="$(printf "This test group adds two instances of your class with the + operator,\n$GENERALHINT")"
group GD-height-add 20
for i in {01..10}; do
tc height-add-$i random_generator height "__add__"
hint height-add-$i "$GDHINT"
done

GEHINT="$(printf "This test group asks an instance of your class for conversion to centimeters,\n$GENERALHINT")"
group GE-height-cm 20
for i in {01..10}; do
tc height-cm-$i random_generator height "cm"
hint height-cm-$i "$GEHINT"
done