#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code/main.py

compile random_generator.py

# sample 01

tc sample-test-01 random_generator 10 1
for i in {01..98}; do
    tc random-$i random_generator -1 $i
done;
