#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01
sample 02
sample 03

for i in {01..20}; do
    tc first-$i random_generator $i $i first
done;

for i in {01..20}; do
    tc last-$i random_generator $i $i last
done;

for i in {01..60}; do
    tc random-$i random_generator 1 20 random
done;
