#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01
sample 02
sample 03

for i in {01..10}; do
for j in {01..04}; do
tc $i-waves-$j random_generator $i $i 2 999
done;
tc $i-waves-05 random_generator $i $i 1 1
tc $i-waves-06 random_generator $i $i 1000 1000
done;
