#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01 # 0 0 0
sample 02 # 0 0 1
sample 03 # 1 1 1
sample 04 # 1 0 0
sample 05 # 1 1 0

tc secret-03 random_generator 0 1 0
tc secret-04 random_generator 0 1 1
tc secret-06 random_generator 1 0 1
