#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01
sample 02

tc random-$i-oneline random_generator 0 10000 1 1
for i in {01..10}; do
    tc random-$i-shorter random_generator 0 10000 2 10 
done;
for i in {01..40}; do
    tc random-$i-longer random_generator 0 10000 11 100 
done;
