#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01
sample 02
sample 03
sample 04
sample 05

tc edge-01 random_generator "integer" 0 0
tc edge-02 random_generator "integer" 1000 1000
tc edge-03 random_generator "string" 0
tc edge-04 random_generator "infinity" 0
tc edge-05 random_generator "infinity" 1
tc edge-06 random_generator "NaN"
tc edge-07 random_generator "dot"
tc edge-08 random_generator "multiple_dots"


for i in {01..10}; do
tc random-$i random_generator "float" 0.01 999.99 2
done;

for i in {11..20}; do
tc random-$i random_generator "string" 4
done;

for i in {21..30}; do
tc random-$i random_generator "sci_notation"
done;

for i in {31..40}; do
tc random-$i random_generator "leading_zero" -10000 10000 1
done;

for i in {41..50}; do
tc random-$i random_generator "leading_zero" -10000 10000 0
done;

for i in {51..70}; do
tc random-$i random_generator "string-integer" 5
done;

for i in {71..90}; do
tc random-$i random_generator "string-float"
done;

for i in {91..100}; do
tc random-$i random_generator "no_leading_decimal_zero_int" -10000 10000
done;

for i in {101..110}; do
tc random-$i random_generator "float_underscore" -10000 10000 6
done;