#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01
sample 02

for i in {01..30}; do
tc random-$i random_generator 1 999999999 0
done;
for i in {31..39}; do
tc random-$i random_generator 0 999999999 1
done;
for i in {41..49}; do
tc random-$i random_generator 0 1 0
done;
tc random-50 random_generator 0 0 0
