#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01
sample 02
sample 03
sample 04

tc sample-01 random_generator 1
tc sample-02 random_generator 2
tc sample-03 random_generator 3
tc sample-04 random_generator 4
