#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01

for i in {01..10}; do
    tc small-random-$i random_generator 1 10
done;

for i in {11..20}; do
    tc big-random-$i random_generator 20 49
done;
