#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01
sample 02
sample 03
sample 04
sample 05

for i in {01..40}; do
tc random-$i random_generator -1000000 1000000 0
done;

for i in {41..50}; do
tc random-$i random_generator -1000000 1000000 1
done;
