#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile fixed_generator.py

sample 01
sample 02
sample 03
sample 04
sample 05

for i in {2,4,6,7,8}; do
tc fixed-$i fixed_generator "$i"
done;
