#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01
sample 02


for i in {01..10}; do
    tc random-small-$i random_generator 10 20 1 2
done;

for i in {11..20}; do
    tc random-small-$i random_generator 10 20 1 1
done;

for i in {01..20}; do
    tc random-medium-$i random_generator 20 50 1 2
done;
