#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01
sample 02
sample 03

for i in {01..99}; do
tc allcase-$i random_generator $i
done;

tc allcase-100 random_generator 100
