#!/usr/bin/env bash
PPATH=$(realpath ..)
    USE_SCORING=0
    . ../../../../testdata_tools/gen.sh

    use_solution solution_code.py

    compile random_generator.py

    sample 01
    sample 02
    sample 03


for discs in {01..02}; do
    tc case-$discs random_generator $discs
done;
for discs in {06..09}; do
    tc case-$discs random_generator $discs
done;
