#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01
sample 02
sample 03

for i in {01..10}; do
    tc random-small-$i random_generator 10 20
done;

for i in {11..30}; do
    tc random-small-$i random_generator 20 100
done;
