#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01
sample 02
sample 03
sample 04
sample 05

for i in {01..30}; do
    tc random-$i random_generator 1 5 0 5 -1 1
done;
for i in {31..60}; do
    tc random-$i random_generator 1 20 0 20 -10 10
done;
for i in {61..90}; do
    tc random-$i random_generator 1 70 0 70 -100 100
done;
