#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01
sample 02
sample 03
for s in {01..05}; do 
 for i in {01..10}; do
  tc random-$s-$i random_generator 1 2000 $s
 done;
done;
tc random-06 random_generator 1 2000 10
tc random-07 random_generator 1 2000 50
tc random-08 random_generator 1 2000 42
tc edge-01 random_generator 1 2000 100
