#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01
sample 02

tc edge-01 random_generator 0 0

for i in {01..20}; do
    tc random-$i random_generator 10 50
done;
