#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01
sample 02
sample 03
sample 04
sample 05

for i in {003..100}; do
    if [ "$i" -eq "005" ] || [ "$i" -eq "008" ] || [ "$i" -eq "016" ]; then
        continue
    fi
    tc size-$i random_generator $i $i
done;
