#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01
sample 02
sample 03
sample 04

for i in {01..10}; do
tc rand-nonum-$i random_generator nonumberincluded
done;
for i in {01..40}; do
tc rand-num-$i random_generator numberincluded
done;
