#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01
sample 02
sample 03
sample 04

for i in {01..25}; do
tc random-$i random_generator 0 1000000
done;

for i in {26..50}; do
tc random-$i random_generator -1000000 1000000
done;
