#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01
sample 02
sample 03
sample 04

tc edge-01 random_generator 0 0
tc edge-02 random_generator 1000 1000

for i in {01..50}; do
tc random-$i random_generator 0.01 999.99
done;
