#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01
sample 02
sample 03

for i in {01..05}; do
    tc single-grade-$i random_generator 1 1 1 1
done;

for i in {06..10}; do
    tc one-per-student-$i random_generator 2 10 1 1
done;

for i in {11..15}; do
    tc single-student-$i random_generator 1 1 2 5
done;

for i in {16..20}; do
    tc multiple-$i random_generator 2 10 2 5
done;

for i in {21..25}; do
    tc random-$i random_generator 2 10 1 20
done;
