#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01
sample 02
sample 03

tc max random_generator 1000000 1000000 100000 100000
for i in {01..30}; do
tc random-$i random_generator 1 1000000 1 100000
done;
