#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01
sample 02
sample 03
sample 04
sample 05
sample 06
sample 07

for i in {01..40}; do
tc random-false-$i random_generator nomatch 5 70
done;
for i in {01..40}; do
tc random-true-$i random_generator match 5 70
done;
