#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py
compile edge_case_generator.py

sample 01
sample 02
sample 03

for i in {01..10}; do
tc random-$i random_generator
done;

tc edge-case-01 edge_case_generator 1000
