#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01
sample 02
sample 03
sample 04
sample 05

for i in {02..100}; do
    if [[ $i != 003 ]] && [[ $i != 005 ]] && [[ $i != 042 ]]; then
        tc secret-$i random_generator $i $i
    fi
done;
