#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01
sample 02

tc edge-01 random_generator "aa"
tc edge-02 random_generator "ac"
tc edge-03 random_generator "ba"
tc edge-04 random_generator "bb"
tc edge-05 random_generator "bc"
tc edge-06 random_generator "cb"
tc edge-07 random_generator "cc"