#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../../testdata_tools/gen.sh

use_solution solution_code.py

compile random_generator.py

sample 01
sample 02

tc edge-01 random_generator 100

for i in {01..99..8}; do
    tc sequence-$i random_generator $i
done;
